#!/bin/bash

RED='\033[0;31m'
NC='\033[0m' # No Color

print_error() {
  echo -e "${RED}$1${NC}"
}

if [ -z "$GOOGLE_API_KEY" ]; then
  print_error "Error: GOOGLE_API_KEY is not set. Please create an API key at https://aistudio.google.com/apikey and set it as an environment variable."
  exit 1
fi

if ! command -v jq &> /dev/null
then
  echo "jq could not be found, installing..."
  if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    sudo apt-get update && sudo apt-get install -y jq
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    brew install jq
  else
    print_error "Unsupported OS. Please install jq manually."
    exit 1
  fi
fi

CACHE_FILE="/tmp/gemini_cache_id.txt"

TEMP_CONSOLIDATED_CODE_FILE=$(mktemp /tmp/gemini-code-analyzer-context.txt)
TEMP_REQUEST_FILE=$(mktemp /tmp/cache_request.json)
TEMP_CACHE_JSON_RESPONSE=$(mktemp /tmp/cache.json)
trap "rm -f $TEMP_CONSOLIDATED_CODE_FILE $TEMP_REQUEST_FILE $TEMP_CACHE_JSON_RESPONSE" EXIT

# Finds all the files in the directories & sub-directories and puts them in a single file
# https://github.com/simonw/files-to-prompt
consolidate_files() {
  if ! command -v files-to-prompt &> /dev/null
  then
    pip3 install files-to-prompt
  fi

  files-to-prompt "$@" -o "$TEMP_CONSOLIDATED_CODE_FILE"
}

# https://ai.google.dev/gemini-api/docs/caching?lang=rest
# https://ai.google.dev/api/caching
# model - only 1.5 Flash has caching right now -- 2.0 Flash and 2.0 Flash-Lite caching will be available 3/31/2025: https://ai.google.dev/gemini-api/docs/pricing
# mime_types - https://www.iana.org/assignments/media-types/media-types.xhtml#text
# systemInstruction - System Prompt
# ttl - Default is 1 hr
cache() {
  if [ $# -lt 1 ]; then
    print_error "Error: No files/directories specified for caching."
    print_error "Usage: $0 cache <FILES/DIRECTORIES> [<FILES/DIRECTORIES> ...]"
    exit 1
  fi

  consolidate_files "$@"
  echo '{
    "model": "models/gemini-1.5-flash-001",
    "contents":[
      {
        "parts":[
          {
            "inline_data": {
              "mime_type":"text/plain",
              "data": "'$(base64 -i "$TEMP_CONSOLIDATED_CODE_FILE")'"
            }
          }
        ],
      "role": "user"
      }
    ],
    "systemInstruction": {
      "parts": [
        {
          "text": "You are an expert at analyzing transcripts."
        }
      ]
    },
    "ttl": "300s"
  }' > "$TEMP_REQUEST_FILE"

  curl -X POST "https://generativelanguage.googleapis.com/v1beta/cachedContents?key=$GOOGLE_API_KEY" \
   -H 'Content-Type: application/json' \
   -d @"$TEMP_REQUEST_FILE" \
   > "$TEMP_CACHE_JSON_RESPONSE"

  if jq -e '.error' "$TEMP_CACHE_JSON_RESPONSE" > /dev/null; then
    print_error "Error: $(jq -r '.error.message' "$TEMP_CACHE_JSON_RESPONSE")"
    exit 1
  fi

  CACHE_ID=$(jq -r '.name' "$TEMP_CACHE_JSON_RESPONSE" | sed 's/cachedContents\///')
  echo "$CACHE_ID" > "$CACHE_FILE"

  echo "Cache created with ID: $CACHE_ID"
  echo
  echo "You can start querying using this cache ID as the first argument in the 'ask' command."
  echo "Example: ./codeai ask 'Your query here'"
}

# Other output options: https://ai.google.dev/gemini-api/docs/text-generation?lang=rest
ask() {
  if [ $# -lt 1 ]; then
    print_error "Error: No query message specified."
    print_error "Usage: $0 ask <QUERY_MESSAGE>"
    exit 1
  fi

  if [ ! -f "$CACHE_FILE" ]; then
    print_error "Error: Cache ID not found. Please run the 'cache' command first."
    exit 1
  fi

  local CACHE_ID=$(cat "$CACHE_FILE")
  local QUERY_MESSAGE=$@

  echo "Asking your question, this may take a few seconds..."

  RESPONSE=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-001:generateContent?key=$GOOGLE_API_KEY" \
  -H 'Content-Type: application/json' \
  -d '{
        "contents": [
          {
            "parts":[{
              "text": "'"$QUERY_MESSAGE"'"
            }],
            "role": "user"
          }
        ],
        "cachedContent": "cachedContents/'"$CACHE_ID"'"
      }')

  if echo "$RESPONSE" | grep -q '"code": 403'; then
    print_error "APIError: $(echo "$RESPONSE" | jq -r '.error.message')"
    print_error "Error: CachedContent not found (or permission denied). Please make sure you call 'cache' first."
    exit 1
  elif echo "$RESPONSE" | jq -e '.error' > /dev/null; then
    print_error "APIError: $(echo "$RESPONSE" | jq -r '.error.message')"
    exit 1
  else
    echo $RESPONSE | jq -r '.candidates[0].content.parts[0].text'
  fi
}

if [ "$1" == "cache" ]; then
  shift
  cache "$@"
elif [ "$1" == "ask" ]; then
  shift
  ask "$@"
else
  echo "Usage: $0 {cache|ask} ..."
fi